#include "rfdc_init.h"

#include "xparameters.h"
#include "xstatus.h"
#include "xil_printf.h"

#include "Si5381A-programming.h"

int RFdc_Init(XRFdc *RFdcInst)
{
    XRFdc_Config *RFdcConfig;
    u32 Status;

    // Program external clock generator (Si5381)
    Status = ProgramSi5381();
    if (Status != XST_SUCCESS) {
        xil_printf("ERROR: ProgramSi5381 failed\n\r");
        return XST_FAILURE;
    }

    // Get RFDC configuration generated by Vivado
    RFdcConfig = XRFdc_LookupConfig(XPAR_USP_RF_DATA_CONVERTER_0_DEVICE_ID);
    if (RFdcConfig == NULL) {
        xil_printf("ERROR: XRFdc_LookupConfig failed\n\r");
        return XST_FAILURE;
    }

    // Initialize RFDC driver
    Status = XRFdc_CfgInitialize(RFdcInst, RFdcConfig);
    if (Status != XRFDC_SUCCESS) {
        xil_printf("ERROR: XRFdc_CfgInitialize failed: %d\n\r", Status);
        return XST_FAILURE;
    }

    xil_printf("RFDC CfgInitialize OK\n\r");

    // Search for the ADC/DAC tiles enabled in the design and start them
    for (int i = 0; i < 4; i++) {

        if (RFdcConfig->DACTile_Config[i].Enable) {
            xil_printf("Starting DAC tile %d\n\r", i);

            Status = XRFdc_StartUp(RFdcInst, XRFDC_DAC_TILE, i);
            if (Status != XRFDC_SUCCESS) {
                xil_printf("ERROR: DAC tile %d StartUp failed: %d\n\r", i, Status);
                return XST_FAILURE;
            }

            xil_printf("DAC tile %d StartUp OK\n\r", i);
        }

        if (RFdcConfig->ADCTile_Config[i].Enable) {
            xil_printf("Starting ADC tile %d\n\r", i);

            Status = XRFdc_StartUp(RFdcInst, XRFDC_ADC_TILE, i);
            if (Status != XRFDC_SUCCESS) {
                xil_printf("ERROR: ADC tile %d StartUp failed: %d\n\r", i, Status);
                return XST_FAILURE;
            }

            xil_printf("ADC tile %d StartUp OK\n\r", i);
        }
    }

    xil_printf("RFDC init complete\n\r");

    return XST_SUCCESS;
}
